kind: project
metadata:
  name: test-print
spec:
  functions:
  - name: test-print
    spec:
      kind: job
      metadata:
        name: test-print
        tag: ''
        hash: 2a5e34ddb0155443a5ebf569383f59226a037959
        project: test-print
        labels:
          author: gbh
      spec:
        command: ''
        args: []
        image: iguazioregistry.azurecr.io/mlrun-dask:dev115
        env: []
        default_handler: test_print
        entry_points:
          test_print:
            name: test_print
            doc: Basic function to verify execution
            parameters:
            - name: context
              type: MLClientCtx
              doc: mlrun context
              default: ''
            outputs:
            - default: ''
            lineno: 8
        description: Pass an notification to the specified Teams channel on pipeline
          failure
        build:
          functionSourceCode: IyBHZW5lcmF0ZWQgYnkgbnVjbGlvLmV4cG9ydC5OdWNsaW9FeHBvcnRlcgoKaW1wb3J0IHdhcm5pbmdzCndhcm5pbmdzLnNpbXBsZWZpbHRlcihhY3Rpb249Imlnbm9yZSIsIGNhdGVnb3J5PUZ1dHVyZVdhcm5pbmcpCgpmcm9tIG1scnVuLmV4ZWN1dGlvbiBpbXBvcnQgTUxDbGllbnRDdHgKCmRlZiB0ZXN0X3ByaW50KAogICAgY29udGV4dDogTUxDbGllbnRDdHgsCik6CiAgICAiIiIKICAgIEJhc2ljIGZ1bmN0aW9uIHRvIHZlcmlmeSBleGVjdXRpb24KICAgIAogICAgOnBhcmFtIGNvbnRleHQ6IG1scnVuIGNvbnRleHQKICAgICIiIgoKICAgIGNvbnRleHQubG9nZ2VyLmluZm8oIlJhbiBzdWNjZXNzZnVsbHkiKQoK
          commands: []
          code_origin: https://ecolab@dev.azure.com/Ecolab/AdvancedAnalytics/_git/functions#1ecb579d86d31bc7469addf9e6b2faacc149f8e4
        image_pull_secret: iguazio-registry
        affinity: null
      verbose: false
  workflows:
  - name: main
    path: /User/functions/test_print/workflow.py
  artifacts: []
  artifact_path: /v3io/projects/{{run.project}}/artifacts
  source: ''
  subpath: ''
  origin_url: ''
  desired_state: online
